# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f9f59411ab5807f640abbc7ebd10ebcd05837911abbf66f9624dfa45bf27b4802948cfe5657667b47e2a387ac76b9d7d2db90494fabb1bcaa94ad8c140e9427

test:
  secret_key_base: d2e3c171deb201ac51e7074ce6ec8271ab8e9f8a2405242a80816451f8e2ca1b55a1479960a4518df88f7a495e04f0d973ccc092298ccd1fa45b9e2509f65154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
